import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Typescript Jest App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello world!</h1>
      </main>
    </>
  );
}
